import type { EditorPreference } from '@blog/types';

import { defaultNodeStyleConfig } from './nodeStyles';

export const defaultEditorPreference: EditorPreference = {
  version: 1,
  theme: {
    rootClassName: 'editor-theme-default',
    textColor: 'var(--color-fg)',
    caretColor: 'var(--color-fg-deeper)',
    placeholderColor: 'var(--color-fg-light)',
    selection: {
      backgroundColor: 'var(--color-selection-bg)',
      color: 'var(--color-selection-fg)',
    },
    paragraph: {
      fontFamily: 'inherit',
      fontSize: '1rem',
      fontWeight: '400',
      lineHeight: '1.75',
      color: 'var(--color-fg)',
      marginTop: '0.5rem',
      marginBottom: '0.5rem',
      minHeight: '1.75em',
    },
    headings: {
      h1: {
        fontFamily: 'inherit',
        fontSize: '2rem',
        fontWeight: '700',
        lineHeight: '1.25',
        color: 'var(--color-fg-deeper)',
        marginTop: '2.5rem',
        marginBottom: '1rem',
        paddingBottom: '0.625rem',
        borderBottom: '1px solid var(--border)',
      },
      h2: {
        fontFamily: 'inherit',
        fontSize: '1.5rem',
        fontWeight: '600',
        lineHeight: '1.3',
        color: 'var(--color-fg-deeper)',
        marginTop: '2rem',
        marginBottom: '0.75rem',
        paddingBottom: '0.5rem',
        borderBottom: '1px solid var(--color-fg-lighter)',
      },
      h3: {
        fontFamily: 'inherit',
        fontSize: '1.25rem',
        fontWeight: '600',
        lineHeight: '1.4',
        color: 'var(--color-fg-deep)',
        marginTop: '1.5rem',
        marginBottom: '0.5rem',
      },
      h4: {
        fontFamily: 'inherit',
        fontSize: '1.125rem',
        fontWeight: '600',
        lineHeight: '1.45',
        color: 'var(--color-fg-deep)',
        marginTop: '1.25rem',
        marginBottom: '0.5rem',
      },
      h5: {
        fontFamily: 'inherit',
        fontSize: '1rem',
        fontWeight: '600',
        lineHeight: '1.5',
        color: 'var(--color-fg)',
        marginTop: '1rem',
        marginBottom: '0.5rem',
      },
      h6: {
        fontFamily: 'inherit',
        fontSize: '0.875rem',
        fontWeight: '600',
        lineHeight: '1.55',
        color: 'var(--color-fg-light)',
        marginTop: '1rem',
        marginBottom: '0.5rem',
      },
    },
    blockquote: {
      fontFamily: 'inherit',
      fontSize: '1rem',
      fontWeight: '400',
      lineHeight: '1.7',
      color: 'var(--color-fg-light)',
      marginTop: '1rem',
      marginBottom: '1rem',
      borderColor: 'var(--color-fg-lighter)',
      borderWidth: '3px',
      paddingInlineStart: '1rem',
      fontStyle: 'italic',
    },
    inlineCode: {
      backgroundColor: 'var(--color-hover)',
      textColor: 'var(--color-fg-deeper)',
      borderRadius: '0.375rem',
      paddingInline: '0.375rem',
      paddingBlock: '0.125rem',
      fontSize: '0.875em',
      fontFamily: 'ui-monospace, monospace',
    },
    codeBlock: {
      backgroundColor: '#1e1e1e',
      textColor: '#d4d4d4',
      borderColor: 'var(--border)',
      borderRadius: '0.75rem',
      marginTop: '1rem',
      marginBottom: '1rem',
      paddingX: '1rem',
      paddingY: '1rem',
      fontSize: '0.875rem',
      lineHeight: '1.7',
      fontFamily: 'ui-monospace, monospace',
    },
    link: {
      color: '#60a5fa',
      hoverColor: '#93c5fd',
      underlineOffset: '2px',
    },
    tokens: {},
  },
  nodeStyles: defaultNodeStyleConfig,
};
