import type { CSSProperties } from 'react';

import type { EditorThemeConfig, EditorThemeCssVariableName } from '@blog/types';

export const EDITOR_THEME_ROOT_CLASS_NAME = 'editor-theme-root';

export const EDITOR_THEME_TOKEN_NAMES = [
  '--editor-text-color',
  '--editor-caret-color',
  '--editor-placeholder-color',
  '--editor-selection-bg',
  '--editor-selection-fg',
  '--editor-paragraph-font-family',
  '--editor-paragraph-font-size',
  '--editor-paragraph-font-weight',
  '--editor-paragraph-line-height',
  '--editor-paragraph-color',
  '--editor-paragraph-margin-top',
  '--editor-paragraph-margin-bottom',
  '--editor-paragraph-min-height',
  '--editor-heading-h1-font-family',
  '--editor-heading-h1-font-size',
  '--editor-heading-h1-font-weight',
  '--editor-heading-h1-line-height',
  '--editor-heading-h1-color',
  '--editor-heading-h1-margin-top',
  '--editor-heading-h1-margin-bottom',
  '--editor-heading-h2-font-family',
  '--editor-heading-h2-font-size',
  '--editor-heading-h2-font-weight',
  '--editor-heading-h2-line-height',
  '--editor-heading-h2-color',
  '--editor-heading-h2-margin-top',
  '--editor-heading-h2-margin-bottom',
  '--editor-heading-h3-font-family',
  '--editor-heading-h3-font-size',
  '--editor-heading-h3-font-weight',
  '--editor-heading-h3-line-height',
  '--editor-heading-h3-color',
  '--editor-heading-h3-margin-top',
  '--editor-heading-h3-margin-bottom',
  '--editor-blockquote-font-family',
  '--editor-blockquote-font-size',
  '--editor-blockquote-font-weight',
  '--editor-blockquote-line-height',
  '--editor-blockquote-color',
  '--editor-blockquote-margin-top',
  '--editor-blockquote-margin-bottom',
  '--editor-blockquote-border-color',
  '--editor-blockquote-border-width',
  '--editor-blockquote-padding-inline-start',
  '--editor-blockquote-font-style',
  '--editor-inline-code-background',
  '--editor-inline-code-color',
  '--editor-inline-code-border-radius',
  '--editor-inline-code-padding-inline',
  '--editor-inline-code-padding-block',
  '--editor-inline-code-font-size',
  '--editor-inline-code-font-family',
  '--editor-code-block-background',
  '--editor-code-block-color',
  '--editor-code-block-border-color',
  '--editor-code-block-border-radius',
  '--editor-code-block-margin-top',
  '--editor-code-block-margin-bottom',
  '--editor-code-block-padding-x',
  '--editor-code-block-padding-y',
  '--editor-code-block-font-size',
  '--editor-code-block-line-height',
  '--editor-code-block-font-family',
  '--editor-link-color',
  '--editor-link-hover-color',
  '--editor-link-underline-offset',
] as const satisfies readonly EditorThemeCssVariableName[];

export type EditorThemeStyle = CSSProperties & Partial<Record<EditorThemeCssVariableName, string>>;

export function buildEditorThemeStyle(themeConfig: EditorThemeConfig): EditorThemeStyle {
  const themeVariables: Partial<Record<EditorThemeCssVariableName, string>> = {
    '--editor-text-color': themeConfig.textColor,
    '--editor-caret-color': themeConfig.caretColor,
    '--editor-placeholder-color': themeConfig.placeholderColor,
    '--editor-selection-bg': themeConfig.selection.backgroundColor,
    '--editor-selection-fg': themeConfig.selection.color,
    '--editor-paragraph-font-family': themeConfig.paragraph.fontFamily ?? 'inherit',
    '--editor-paragraph-font-size': themeConfig.paragraph.fontSize,
    '--editor-paragraph-font-weight': themeConfig.paragraph.fontWeight,
    '--editor-paragraph-line-height': themeConfig.paragraph.lineHeight,
    '--editor-paragraph-color': themeConfig.paragraph.color,
    '--editor-paragraph-margin-top': themeConfig.paragraph.marginTop,
    '--editor-paragraph-margin-bottom': themeConfig.paragraph.marginBottom,
    '--editor-paragraph-min-height': themeConfig.paragraph.minHeight,
    '--editor-heading-h1-font-family': themeConfig.headings.h1.fontFamily ?? 'inherit',
    '--editor-heading-h1-font-size': themeConfig.headings.h1.fontSize,
    '--editor-heading-h1-font-weight': themeConfig.headings.h1.fontWeight,
    '--editor-heading-h1-line-height': themeConfig.headings.h1.lineHeight,
    '--editor-heading-h1-color': themeConfig.headings.h1.color,
    '--editor-heading-h1-margin-top': themeConfig.headings.h1.marginTop,
    '--editor-heading-h1-margin-bottom': themeConfig.headings.h1.marginBottom,
    '--editor-heading-h2-font-family': themeConfig.headings.h2.fontFamily ?? 'inherit',
    '--editor-heading-h2-font-size': themeConfig.headings.h2.fontSize,
    '--editor-heading-h2-font-weight': themeConfig.headings.h2.fontWeight,
    '--editor-heading-h2-line-height': themeConfig.headings.h2.lineHeight,
    '--editor-heading-h2-color': themeConfig.headings.h2.color,
    '--editor-heading-h2-margin-top': themeConfig.headings.h2.marginTop,
    '--editor-heading-h2-margin-bottom': themeConfig.headings.h2.marginBottom,
    '--editor-heading-h3-font-family': themeConfig.headings.h3.fontFamily ?? 'inherit',
    '--editor-heading-h3-font-size': themeConfig.headings.h3.fontSize,
    '--editor-heading-h3-font-weight': themeConfig.headings.h3.fontWeight,
    '--editor-heading-h3-line-height': themeConfig.headings.h3.lineHeight,
    '--editor-heading-h3-color': themeConfig.headings.h3.color,
    '--editor-heading-h3-margin-top': themeConfig.headings.h3.marginTop,
    '--editor-heading-h3-margin-bottom': themeConfig.headings.h3.marginBottom,
    '--editor-blockquote-font-family': themeConfig.blockquote.fontFamily ?? 'inherit',
    '--editor-blockquote-font-size': themeConfig.blockquote.fontSize,
    '--editor-blockquote-font-weight': themeConfig.blockquote.fontWeight,
    '--editor-blockquote-line-height': themeConfig.blockquote.lineHeight,
    '--editor-blockquote-color': themeConfig.blockquote.color,
    '--editor-blockquote-margin-top': themeConfig.blockquote.marginTop,
    '--editor-blockquote-margin-bottom': themeConfig.blockquote.marginBottom,
    '--editor-blockquote-border-color': themeConfig.blockquote.borderColor,
    '--editor-blockquote-border-width': themeConfig.blockquote.borderWidth,
    '--editor-blockquote-padding-inline-start': themeConfig.blockquote.paddingInlineStart,
    '--editor-blockquote-font-style': themeConfig.blockquote.fontStyle,
    '--editor-inline-code-background': themeConfig.inlineCode.backgroundColor,
    '--editor-inline-code-color': themeConfig.inlineCode.textColor,
    '--editor-inline-code-border-radius': themeConfig.inlineCode.borderRadius,
    '--editor-inline-code-padding-inline': themeConfig.inlineCode.paddingInline,
    '--editor-inline-code-padding-block': themeConfig.inlineCode.paddingBlock,
    '--editor-inline-code-font-size': themeConfig.inlineCode.fontSize,
    '--editor-inline-code-font-family': themeConfig.inlineCode.fontFamily,
    '--editor-code-block-background': themeConfig.codeBlock.backgroundColor,
    '--editor-code-block-color': themeConfig.codeBlock.textColor,
    '--editor-code-block-border-color': themeConfig.codeBlock.borderColor,
    '--editor-code-block-border-radius': themeConfig.codeBlock.borderRadius,
    '--editor-code-block-margin-top': themeConfig.codeBlock.marginTop,
    '--editor-code-block-margin-bottom': themeConfig.codeBlock.marginBottom,
    '--editor-code-block-padding-x': themeConfig.codeBlock.paddingX,
    '--editor-code-block-padding-y': themeConfig.codeBlock.paddingY,
    '--editor-code-block-font-size': themeConfig.codeBlock.fontSize,
    '--editor-code-block-line-height': themeConfig.codeBlock.lineHeight,
    '--editor-code-block-font-family': themeConfig.codeBlock.fontFamily,
    '--editor-link-color': themeConfig.link.color,
    '--editor-link-hover-color': themeConfig.link.hoverColor,
    '--editor-link-underline-offset': themeConfig.link.underlineOffset,
    ...themeConfig.tokens,
  };

  return themeVariables as EditorThemeStyle;
}

export function getEditorThemeRootClassNames(themeConfig: Pick<EditorThemeConfig, 'rootClassName'>): string[] {
  return [EDITOR_THEME_ROOT_CLASS_NAME, themeConfig.rootClassName].filter(Boolean);
}
